import streamlit as st
import pandas as pd
import os
import sys

# ==========================================
# 0. Path Fix (CRITICAL)
# ==========================================
# Add the project root directory to sys.path so we can import from 'src'
# This allows the script to see 'src.visualization' regardless of where you run it from
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

# Now imports will work
from streamlit_folium import st_folium
from src.visualization import plot_department_map

# ==========================================
# 1. Page Configuration
# ==========================================
st.set_page_config(
    page_title="French Gas Prices Dashboard",
    page_icon="⛽",
    layout="wide"
)

st.title("⛽ French Gas Price Analysis (2022-2024)")
st.markdown("### Interactive Dashboard for Project Evaluation")

# ==========================================
# 2. Load Data (Cached for performance)
# ==========================================
@st.cache_data
def load_data():
    """
    Loads the cleaned data from the Parquet file generated by the Spark Notebook.
    """
    # Robust path handling:
    # We construct the path relative to the project root we defined earlier
    file_path = os.path.join(project_root, "data", "processed", "gas_prices_clean.parquet")
    
    # Check if file exists
    if not os.path.exists(file_path):
        return None
        
    # Read Parquet using Pandas
    return pd.read_parquet(file_path)

df = load_data()

# Error handling if data is missing
if df is None:
    st.error("⚠️ Data file not found!")
    st.warning("Please run your Spark Notebook first to generate 'data/processed/gas_prices_clean.parquet'.")
    st.code(f'# Expected path:\n{os.path.join(project_root, "data", "processed", "gas_prices_clean.parquet")}', language='python')
    st.stop()

# ==========================================
# 3. Sidebar Filters
# ==========================================
st.sidebar.header("Configuration")

# Filter by Year
all_years = sorted(df['year'].unique())
selected_years = st.sidebar.multiselect(
    "Select Years", 
    options=all_years, 
    default=all_years
)

# Filter by Gas Type
all_gas = sorted(df['name'].unique())
selected_gas = st.sidebar.multiselect(
    "Select Gas Types", 
    options=all_gas, 
    default=all_gas
)

# Apply Filters
mask = (df['year'].isin(selected_years)) & (df['name'].isin(selected_gas))
df_filtered = df[mask]

# ==========================================
# 4. Key Metrics
# ==========================================
col1, col2, col3 = st.columns(3)
col1.metric("Total Records", f"{len(df_filtered):,}")

if not df_filtered.empty:
    col2.metric("Avg Price (Selected)", f"€ {df_filtered['prix'].mean():.3f}")
    col3.metric("Stations Monitored", f"{df_filtered['id'].nunique():,}")
else:
    col2.metric("Avg Price", "0")
    col3.metric("Stations Monitored", "0")

st.markdown("---")

# ==========================================
# 5. Visualizations (Tabs)
# ==========================================
tab1, tab2, tab3, tab4 = st.tabs(["📊 Weekly Evolution", "📅 Daily Trends", "🗺️ Geographic Map", "🔍 Raw Data"])

# --- TAB 1: Weekly Evolution (Page 6) ---
with tab1:
    st.subheader("Weekly Evolution of Average Gas Prices")
    st.markdown("**Requirement:** X=Week Index, Y=Avg Price")
    
    if not df_filtered.empty and 'week_index' in df_filtered.columns:
        # Aggregate
        weekly_data = df_filtered.groupby(['week_index', 'name'])['prix'].mean().reset_index()
        weekly_data = weekly_data.sort_values(by=['week_index'])
        
        # Plot
        st.line_chart(
            data=weekly_data,
            x='week_index',
            y='prix',
            color='name',
            height=500,
            use_container_width=True
        )
    else:
        st.info("No data available or 'week_index' missing.")

# --- TAB 2: Daily Trends ---
with tab2:
    st.subheader("Daily Price Movements")
    
    if not df_filtered.empty:
        daily_data = df_filtered.groupby(['day_date', 'name'])['prix'].mean().reset_index()
        st.line_chart(
            data=daily_data,
            x='day_date',
            y='prix',
            color='name',
            height=450
        )

# --- TAB 3: Geographic Map (Bonus Phase 5) ---
with tab3:
    st.subheader("🗺️ Geographic Distribution (Price Index)")
    
    # Selector specific to map
    target_gas_map = st.selectbox("Select Gas for Map", df['name'].unique(), key="map_select")
    
    # Prepare Map Data
    # 1. Create 'dept' column if it doesn't exist (fixing 'cp' to 5 digits first)
    # We use the full 'df' here to avoid empty maps if sidebar filters are too strict
    df_map_source = df[df['name'] == target_gas_map].copy()
    
    df_map_source['cp_fixed'] = df_map_source['cp'].astype(str).str.zfill(5)
    df_map_source['dept'] = df_map_source['cp_fixed'].str[:2]
    
    # 2. Aggregate
    map_data = df_map_source.groupby('dept')['price_index'].mean().reset_index()
    
    # 3. Generate Map
    if not map_data.empty:
        # Call the function from src/visualization.py
        m = plot_department_map(map_data, target_gas_map, metric_col="price_index")
        
        # Display with Streamlit-Folium
        st_folium(m, width=800, height=600)
    else:
        st.warning(f"No data found for {target_gas_map}")

# --- TAB 4: Raw Data ---
with tab4:
    st.subheader("Dataset Explorer")
    st.dataframe(df_filtered.head(1000))